voyages/apps/contribute/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from voyages.apps.contribute import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^guidelines', TemplateView.as_view(template_name='contribute/guidelines.html'), name='guidelines'),

    url(r'^thanks', TemplateView.as_view(template_name='contribute/thanks.html'), name='thanks'),
    
    url(r'^delete_voyage', views.delete, name='delete_voyage'),

    url(r'^delete_review/(?P<contribution_id>\d+)', views.delete_review, name='delete_review'),

    url(r'^places_ajax', views.get_places, name='places_ajax'),

    url(r'^voyage_ajax', views.get_voyage_by_id, name='voyage_ajax'),
    
    url(r'^interim/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)/save_ajax$',
        views.interim_save_ajax, name='interim_save_ajax'),

    url(r'interim/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)',
        views.interim, name='interim'),

    url(r'interim_commit/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)',
        views.interim_commit, name='interim_commit'),

    url(r'interim_summary/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)$',
        views.interim_summary, name='interim_summary'),

    url(r'interim_summary/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)/(?P<mode>reviewer)$',
        views.interim_summary, name='interim_summary_reviewer'),

    url(r'interim_summary/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)/(?P<mode>editor)$',
        views.interim_summary, name='interim_summary_editor'),
        
    url(r'legal', views.legal, name='legal'),

    url(r'edit_voyage', views.edit, name='edit_voyage'),

    url(r'merge_voyages', views.merge, name='merge_voyages'),

    url(r'new_voyage', views.new_voyage, name='new_voyage'),

    url(r'editor_main', views.editor_main, name='editor_main'),

    url(r'review_request/(?P<review_request_id>\d+)',
        views.review_request, name='review_request'),
    url(r'reply_review_request', views.reply_review_request, name='reply_review_request'),
    
    url(r'editorial_review/(?P<editor_contribution_id>\d+)/save_ajax', views.editorial_review_interim_save_ajax, name='editorial_review_interim_save_ajax'),
    url(r'editorial_review/(?P<editor_contribution_id>\d+)/submit_editorial_decision', views.submit_editorial_decision, name='submit_editorial_decision'),
    url(r'editorial_review/(?P<review_request_id>\d+)', views.editorial_review, name='editorial_review'),
    
    url(r'editorial_sources', views.editorial_sources, name='editorial_sources'),
    
    url(r'begin_editorial_review', views.begin_editorial_review, name='begin_editorial_review'),
        
    url(r'review/(?P<reviewer_contribution_id>\d+)/save_ajax', views.review_interim_save_ajax, name='review_interim_save_ajax'),
    url(r'review/(?P<review_request_id>\d+)/submit_review_to_editor', views.submit_review_to_editor, name='submit_review_to_editor'),
    url(r'review/(?P<review_request_id>\d+)', views.review, name='review'),

    url(r'json_pending_requests', views.get_pending_requests, name='json_pending_requests'),
    url(r'json_pending_publication', views.get_pending_publication, name='json_pending_publication'),
    url(r'json_reviewers', views.get_reviewers, name='json_reviewers'),
    url(r'json_publish_pending', views.publish_pending, name='json_publish_pending'),
    url(r'json_retrieve_publication_status', views.retrieve_publication_status, name='json_retrieve_publication_status'),
    url(r'download_voyages_status', views.download_voyages_status, name='download_voyages_status'),
    url(r'download_voyages_go', views.download_voyages_go, name='download_voyages_go'),
    url(r'download_voyages', views.download_voyages, name='download_voyages'),
    
    url(r'post_review_request', views.post_review_request, name='post_review_request'),
    url(r'post_archive_review_request', views.post_archive_review_request, name='post_archive_review_request'),
    
    url(r'impute_contribution/(?P<editor_contribution_id>\d+)', views.impute_contribution, name='impute_contribution'),
    ]

voyages/urls.py
from django.conf import settings
from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
from autocomplete_light import shortcuts as autocomplete_light
autocomplete_light.autodiscover()
from django.contrib import admin

admin.autodiscover()

# Sitemap
from sitemap import StaticSitemap

js_info_dict = {
    'packages': ('voyages',),
}

import voyages.apps.assessment.views
import voyages.apps.voyage.views
import voyages.apps.common.views
import voyages.apps.past.views
import django.contrib.sitemaps.views
import django.views.i18n
import django.views.static

urlpatterns = [
    url(r'^', include('voyages.apps.static_content.urls', namespace='static_content')),
    # Short permalink
    url(r'^estimates/(?P<link_id>\w+)', voyages.apps.assessment.views.restore_permalink, name='restore_e_permalink'),
    url(r'^voyages/(?P<link_id>\w+)', voyages.apps.voyage.views.restore_permalink, name='restore_v_permalink'),
    url(r'^past-db/(?P<link_id>\w+)', voyages.apps.past.views.restore_permalink, name='restore_past_permalink'),

    #Include url handlers of each section
    url(r'^voyage/', include('voyages.apps.voyage.urls', namespace='voyage')),
    url(r'^american/', include('voyages.apps.american.urls', namespace='american')),
    url(r'^assessment/', include('voyages.apps.assessment.urls', namespace='assessment')),
    url(r'^about/', include('voyages.apps.about.urls', namespace='about')),
    url(r'^common/', include('voyages.apps.common.urls', namespace='common')),
    url(r'^past/', include('voyages.apps.past.urls', namespace='past')),
    url(r'^resources/', include('voyages.apps.resources.urls', namespace='resources')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^contribute/', include('voyages.apps.contribute.urls', namespace='contribute')),
    url(r'^search/', include('haystack.urls', namespace='search')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),

    # Handle language changes
    url(r'^setlanguage/(?P<lang_code>\w+)', voyages.apps.common.views.set_language, name='set_lang'),

    # Translation support for javascript code.
    url(r'^jsi18n/', django.views.i18n.javascript_catalog, js_info_dict, name='javascript-catalog'),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^captcha/', include('captcha.urls'))]

# XML generated sitemap
sitemaps = {
    'staticpages': StaticSitemap(urlpatterns),
}
# URLs not included in the sitemap
urlpatterns += [
    url(r'^sitemap\.xml', django.contrib.sitemaps.views.sitemap, {'sitemaps': sitemaps}, name='sitemap-xml'),

    # Flatpages
    url(r'^pages/', include('django.contrib.flatpages.urls')),

    # Adding download files
    url(r'^admin/downloads', voyages.apps.voyage.views.download_file, name="downloads"),

    # Admin documentation
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Admin management
    url(r'^admin/', include(admin.site.urls))]

#Serving static files including files uploaded by users
if settings.DEBUG:
# static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^documents/(?P<path>.*)', django.views.static.serve, {
        'document_root': settings.MEDIA_ROOT})]

voyages/apps/contribute/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.core.urlresolvers import reverse
from django.db import connection, transaction
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest, HttpResponseForbidden, HttpResponseRedirect
from django.http import Http404
from django.views.decorators.http import require_POST
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from voyages.apps.common.views import get_ordered_places
from voyages.apps.contribute.forms import *
from voyages.apps.contribute.models import *
from voyages.apps.voyage.cache import VoyageCache
from voyages.apps.voyage.models import *
from django.utils.html import escape
from django.utils.translation import ugettext as _
from django.core.mail import send_mail
from django.conf import settings
import imputed
import json
import re
import six

number_prefix = 'interim_slave_number_'

def full_contribution_id(contribution_type, contribution_id):
    return contribution_type + '/' + str(contribution_id)

def get_contrib_default_query(model):
    return model.objects.select_related('contributor')

def get_filtered_contributions(filter_args):
    return [{'type': 'edit', 'id': x.pk, 'contribution': x} for x in get_contrib_default_query(EditVoyageContribution).filter(**filter_args)] +\
            [{'type': 'merge', 'id': x.pk, 'contribution': x} for x in get_contrib_default_query(MergeVoyagesContribution).filter(**filter_args)] +\
            [{'type': 'delete', 'id': x.pk, 'contribution': x} for x in get_contrib_default_query(DeleteVoyageContribution).filter(**filter_args)] +\
            [{'type': 'new', 'id': x.pk, 'contribution': x} for x in get_contrib_default_query(NewVoyageContribution).filter(**filter_args)]

def index(request):
    """
    Handles the redirection when user attempts to login
    Display the user index page if the user is already authenticated
    Or return to the login page if the user has not logged in yet
    """
    if request.user.is_authenticated():
        filter_args = {'contributor': request.user, 'status__lte': ContributionStatus.committed}
        contributions = get_filtered_contributions(filter_args)
        review_requests = ReviewRequest.objects.filter(
            suggested_reviewer = request.user, response__lte = 1, archived = False, final_decision = 0)
        return render(
            request, "contribute/index.html",
            {'contributions': contributions, 'review_requests': review_requests})
    else:
        return HttpResponseRedirect(reverse('account_login'))

def legal(request):
    from forms import legal_terms_title
    from forms import legal_terms_paragraph
    return render(request, 'contribute/legal.html',
                  {'title': legal_terms_title, 'paragraph': legal_terms_paragraph})

def get_summary(v):
    dates = v.voyage_dates
    return {'voyage_id': v.voyage_id,
            'captain': ', '.join([c.name for c in v.voyage_captain.all()]),
            'ship': v.voyage_ship.ship_name,
            'year_arrived': dates.get_date_year(dates.first_dis_of_slaves) or
                            dates.get_date_year(dates.imp_arrival_at_port_of_dis)}
                            
def set_isolation_serializable():
    cursor = connection.cursor()
    cursor.execute('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE')

@csrf_exempt
def get_voyage_by_id(request):
    if request.method == 'POST':
        voyage_id = request.POST.get('voyage_id')
        if voyage_id is not None:
            voyage_id = int(voyage_id)
            v = Voyage.all_dataset_objects.filter(voyage_id=voyage_id).first()
            if v is not None:
                summary = get_summary(v)
                # Check whether the voyage already has an open contribution.
                active_statuses = ContributionStatus.active_statuses
                regex = '(^' + str(voyage_id) + '|,' + str(voyage_id) + ')(,|$)'
                is_blocked = EditVoyageContribution.objects.filter(edited_voyage_id=voyage_id, status__in=active_statuses).count() > 0 or \
                    MergeVoyagesContribution.objects.filter(merged_voyages_ids__iregex=regex, status__in=active_statuses).count() > 0 or \
                    DeleteVoyageContribution.objects.filter(deleted_voyages_ids__iregex=regex, status__in=active_statuses).count()
                summary['is_blocked'] = is_blocked
                return JsonResponse(summary)
            else:
                error = 'No voyage found with voyage_id = ' + str(voyage_id)
        else:
            error = 'Missing voyage_id field in POST'
    else:
        error = 'POST request required'
    return JsonResponse({'error': error})

@cache_page(24 * 60 * 60)
@csrf_exempt
def get_places(request):
    # retrieve list of places in the system.
    result = get_ordered_places()
    return JsonResponse(result, safe=False)

@login_required
def delete(request):
    voyage_selection = []
    if request.method == 'POST':
        form = ContributionVoyageSelectionForm(request.POST)
        if form.is_valid():
            ids = form.cleaned_data['ids']
            with transaction.atomic():
                contribution = DeleteVoyageContribution()
                contribution.contributor = request.user
                contribution.status = ContributionStatus.pending
                contribution.deleted_voyages_ids = ','.join([str(x) for x in ids])
                contribution.notes = request.POST.get('notes')
                contribution.save()
            return HttpResponseRedirect(reverse('contribute:delete_review',
                                                kwargs={'contribution_id': contribution.pk}))
        else:
            ids = form.selected_voyages
            voyage_selection = [get_summary(v) for v in Voyage.all_dataset_objects.filter(voyage_id__in=ids)]
    else:
        form = ContributionVoyageSelectionForm()
    return render(request, 'contribute/delete.html', {
        'form': form,
        'voyage_selection': voyage_selection})

@login_required
def delete_review(request, contribution_id):
    contribution = get_object_or_404(DeleteVoyageContribution, pk=contribution_id)
    if request.user.pk != contribution.contributor.pk:
        return HttpResponseForbidden()
    if request.method == 'POST':
        action = request.POST.get('submit_val')
        if action == 'confirm':
            contribution.status = ContributionStatus.committed
            contribution.save()
            return HttpResponseRedirect(reverse('contribute:thanks'))
        elif action == 'cancel':
            contribution.delete()
            return HttpResponseRedirect(reverse('contribute:index'))
        else:
            return HttpResponseBadRequest()
    return delete_review_render(request, contribution, False, 'contributor')

def delete_review_render(request, contribution, readonly, mode):
    from voyages.apps.voyage.views import voyage_variables_data
    ids = [int(pk) for pk in contribution.deleted_voyages_ids.split(',')]
    deleted_voyage_vars = [voyage_variables_data(voyage_id, mode == 'editor')[1] for voyage_id in ids]
    review_request = None
    full_contrib_id = full_contribution_id('delete', contribution.pk)
    if mode != 'contributor':
        # Look for a review request for this delete contribution
        review_request = ReviewRequest.objects.filter(contribution_id=full_contrib_id, archived=False).first()
    return render(request, 'contribute/delete_review.html', {
        'deleted_voyage_vars': deleted_voyage_vars,
        'voyage_selection': ids,
        'readonly': readonly,
        'mode': mode,
        'review_request': review_request,
        'full_contrib_id': full_contrib_id})

@login_required
def edit(request):
    voyage_selection = []
    if request.method == 'POST':
        form = ContributionVoyageSelectionForm(request.POST, max_selection=1)
        if form.is_valid():
            ids = form.cleaned_data['ids']
            with transaction.atomic():
                interim_voyage = InterimVoyage()
                interim_voyage.save()
                contribution = EditVoyageContribution()
                contribution.interim_voyage = interim_voyage
                contribution.contributor = request.user
                contribution.edited_voyage_id = ids[0]
                contribution.status = ContributionStatus.pending
                contribution.save()
                init_interim_voyage(interim_voyage, contribution)
            return HttpResponseRedirect(reverse(
                'contribute:interim', kwargs={'contribution_type': 'edit', 'contribution_id': contribution.pk}
            ))
        else:
            ids = form.selected_voyages
            voyage_selection = [get_summary(v) for v in Voyage.all_dataset_objects.filter(voyage_id=ids[0])] \
                if len(ids) != 0 else []
    else:
        form = ContributionVoyageSelectionForm(max_selection=1)
    return render(request, 'contribute/edit.html', {'form': form, 'voyage_selection': voyage_selection})

@login_required
def merge(request):
    voyage_selection = []
    if request.method == 'POST':
        form = ContributionVoyageSelectionForm(request.POST, min_selection=2)
        if form.is_valid():
            ids = form.cleaned_data['ids']
            with transaction.atomic():
                interim_voyage = InterimVoyage()
                interim_voyage.save()
                contribution = MergeVoyagesContribution()
                contribution.interim_voyage = interim_voyage
                contribution.contributor = request.user
                contribution.merged_voyages_ids = ','.join([str(x) for x in ids])
                contribution.status = ContributionStatus.pending
                contribution.save()
                init_interim_voyage(interim_voyage, contribution)

voyages/apps/contribute/templates/contribute/delete.html
{% extends "account/base.html" %}
{% load i18n %}

{% block center-content %}

<div class="page-title-1" class="contribute_header">{% trans "Recommend the Deletion of an Existing Voyage" %}</div>

<p>
    {% trans "Please use the box for notes to tell us why the selected voyage(s) should be removed from the database." %}
</p>

<p></p>

{% include "contribute/voyage_selection_table.html" %}
<form action="{% url 'contribute:delete_voyage' %}" method="post" class="form-horizontal" style="margin-bottom: 1rem;">
    {% csrf_token %}
    <input type="hidden" name="ids" id="ids_hidden">
    {{ form.ids.errors }}
    <div class="form-group">
        <label for="notes_input">{% trans "Notes:" %}</label>
        <textarea class="form-control" id="notes_input" name="notes"></textarea>
    </div>
</form>

<p>
    <button class="btn btn-solid" id="confirm_btn" onclick="selection.submitForm();">{% trans "Submit" %}</button>
</p>

<script type="text/javascript" src="{{ STATIC_URL }}scripts/contribute/forms.js"></script>
<script type="text/javascript">
    var selection = new VoyageSelection(
        "{% url 'contribute:voyage_ajax' %}",
        [
            {% for voyage in voyage_selection %}
                {{ voyage.voyage_id }},
            {% endfor %}
        ],
        true);
</script>
{% endblock %}

voyages/apps/contribute/templates/contribute/downloads_partial.html
{% load i18n %}

  <div class="page-title-1">{% trans "Downloads" %}</div>

  <div class="page-section">
    <div class="form-check">
      <label class="form-check-label" for="committed">
        <input id="committed_check" name="committed" type="checkbox" class="form-check-input" checked>
        {% trans "Submitted by contributor" %}
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label" for="under_review">
        <input id="under_review_check" name="under_review" type="checkbox" class="form-check-input" checked>
        {% trans "Under review" %}
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label" for="rejected">
        <input id="rejected_check" name="rejected" type="checkbox" class="form-check-input" checked>
        {% trans "Rejected" %}
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label" for="accepted_unpublished">
        <input id="accepted_unpublished_check" name="accepted_unpublished" type="checkbox" class="form-check-input" checked>
        {% trans "Accepted (pending publication)" %}
      </label>
    </div>
    <div class="form-check">
      <label class="form-check-label" for="published">
        <input id="published_check" name="published" type="checkbox" class="form-check-input">
        {% trans "Published" %}
      </label>
    </div>
    <div style="margin-left: 4em;">
      <label for="voyage_type">
        Voyage dataset: 
        <select id="voyage_type_select" name="voyage_type">
          <option value="-1">Both</option>
          <option value="0">Transatlantic</option>
          <option value="1">Intra-American</option>
        </select>
      </label>
    </div>
  </div>

  <div class="page-section">
    <button class="btn btn-solid btn-sm" id="select_all_downloads">{% trans "Select all" %}</button>
    <button class="btn btn-outline btn-sm" id="clear_all_downloads">{% trans "Clear" %}</button>
  </div>

  <div class="page-section">
    <h2>{% trans "Compatibility options" %}</h2>
    <label class="form-check-label" for="remove_linebreaks">
      <input id="remove_linebreaks" name="remove_linebreaks" type="checkbox" class="form-check-input">
      {% trans "Remove line breaks from CSV cells" %}
    </label>
  </div>

  <div class="page-section">
    <button class="btn btn-solid" id="download_selection">{% trans "Download" %}</button>
    <div id="download_link_retry"></div>
    <span id="download_generation_status"></span>
  </div>

<div>
    <span id="last_updated_span"></span>
</div>

<div id="publication_log_pane" class="alert alert-info" style="display: none;">
</div>

<script type="text/javascript">
    var statusChecks = ['accepted_unpublished_check', 'rejected_check', 'under_review_check', 'committed_check', 'published_check'];
    function toggleDownloads(b) {
        for (var i = 0; i < statusChecks.length; ++i) {
            $('#' + statusChecks[i]).prop('checked', b);
        }
    }
    $('#select_all_downloads').click(function() {
        toggleDownloads(true);
    });
    $('#clear_all_downloads').click(function() {
        toggleDownloads(false);
    });
    $('#download_selection').click(function() {
        var postData = {};
        var statusCount = 0;
        for (var i = 0; i < statusChecks.length; ++i) {
            if ($('#' + statusChecks[i]).prop('checked')) {
              postData[statusChecks[i]] = 'True';
              ++statusCount;
            }
        }
        postData.remove_linebreaks = $('#remove_linebreaks').prop('checked') ? 'True' : 'False';
        var voyage_type = parseInt($('#voyage_type_select').val());
        if (voyage_type == 0 || voyage_type == 1) {
          postData.intra_american_flag = voyage_type;
        }
        if (statusCount == 0) {
            alert('{% trans "You must select at least one status" %}');
        } else {
          $.post("{% url 'contribute:download_voyages' %}", postData)
            .fail(function() {
              alert('Server error!');
            })
            .done(function(data) {
              if (data.result == 'OK') {
                $('#download_selection').prop('disabled', true);
                $('#download_link_retry').html('');
                // At this point we have a log_file to monitor.
                // In case the generation is done within a few seconds, we do not bother the user
                // with a message
                var timedCheck = null;
                var onFinished = function() {
                  var downloadUrl = "{% url 'contribute:download_voyages_go' %}?csv_file=" + data.csv_file;
                  window.location = downloadUrl;
                  clearInterval(timedCheck);
                  $('#download_link_retry').html('<a href="' + downloadUrl + '">If the download does not start, click here.</a>');
                  $('#download_selection').prop('disabled', false);
                  $('#download_generation_status').text('');
                };
                var checkCounter = 0;
                var canCheck = true;
                timedCheck = setInterval(function() {
                    if (!canCheck) return;
                    canCheck = false;
                    $.post("{% url 'contribute:download_voyages_status' %}", data)
                      .done(function(statusResult) {
                        statusResult = statusResult.status;
                        if (statusResult && statusResult.includes('FINISHED')) {
                          onFinished();
                        } else if (statusResult && statusResult.includes('ERROR')) {
                          clearInterval(timedCheck);
                          alert(statusResult);
                          $('#download_selection').prop('disabled', false);
                        } else {
                          canCheck = true;
                          if (checkCounter == 0) {
                            alert('The CSV generation has started and may take a while to complete. The download will start once it is ready');
                          }
                          ++checkCounter;
                          $('#download_generation_status').text(statusResult);
                        }
                      });
                  },
                  3000
                );
              } else {
                alert('Server error!');
              }
            });
        }
    });
</script>

voyages/apps/contribute/templates/contribute/edit.html
{% extends "account/base.html" %}
{% load i18n %}

{% block center-content %}

<div class="page-title-1" class="contribute_header">{% trans "Edit an Existing Record of a Voyage" %}</div>

<p>
{% trans "Please select the voyage you wish to edit." %}
</p>

<p>
{% include "contribute/voyage_selection_table.html" %}
</p>

<form action="{% url 'contribute:edit_voyage' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="ids" id="ids_hidden">
    {{ form.ids.errors }}
</form>
<button class="btn btn-solid" id="confirm_btn" onclick="selection.submitForm();">{% trans "Begin" %}</button>

<script type="text/javascript" src="{{ STATIC_URL }}scripts/contribute/forms.js"></script>
<script type="text/javascript">
    var selection = new VoyageSelection(
        "{% url 'contribute:voyage_ajax' %}",
        [
            {% for voyage in voyage_selection %}
                {{ voyage.voyage_id }},
            {% endfor %}
        ],
        false);
</script>
{% endblock %}

voyages/apps/contribute/templates/contribute/index.html
{% extends "account/base.html" %}
{% load i18n %}
{% load sass_tags %}

<!-- The landing page when users log in via contribute login -->

{% block title %}{% trans "User Home" %}{% endblock %}

{% block center-content %}
<link href="{% sass_src 'scss/contribute.scss' %}" rel="stylesheet" type="text/css" />

<div class="white-board">

	<section class="page-section">
	<div class="page-title-1">{% trans "Welcome to the Contribute Section" %}</div>

	{% if request.user.is_staff %}
	<!-- Is enabled only if the user is a staff member -->
		<a class="btn btn-info" href="{% url 'admin:index' %}">{% trans "Live Admin" %}</a></h3>
	{% endif %}
		<a class="btn btn-info" href="{% url 'contribute:new_voyage' %}">{% trans "New Voyage" %}</a>
		<a class="btn btn-info" href="{% url 'contribute:edit_voyage' %}">{% trans "Edit Existing Voyage" %}</a>
		<a class="btn btn-info" href="{% url 'contribute:merge_voyages' %}">{% trans "Merge Voyages" %}</a>
		<a class="btn btn-info" href="{% url 'contribute:delete_voyage' %}">{% trans "Recommend Voyage Deletion" %}</a>
	{% if request.user.is_superuser %}
	<!-- Is enabled only if the user is a super user -->
		<a class="btn btn-info" href="{% url 'contribute:editor_main' %}">{% trans "Editorial Platform" %}</a></h3>
	{% endif %}

	</section>
	<section class="page-section">
	{% for c in contributions %}
		{% if forloop.first %}
			<div class="page-title-1">{% trans "Contributions" %}</div>
			<table class="table table-hover table-striped">
				<thead>
				<tr>
					<th>{% trans "Voyage ID(s)" %}</th>
					<th>{% trans "Type of contribution" %}</th>
					<th>{% trans "Status" %}</th>
				</tr>
				</thead>
				<tbody>
		{% endif %}
					<tr class='clickable-row' data-href="{% url 'contribute:interim' contribution_type=c.type contribution_id=c.id %}">
						<td>
						{{ c.contribution.get_related_voyage_ids|join:", " }}
						<td>{{ c.type }}</td>
						<td>
							{% if c.contribution.status == 0 %}
								{% trans "Pending" %}
							{% elif c.contribution.status == 1 %}
								{% trans "Submitted" %}
							{% elif c.contribution.status == 2 %}
								{% trans "Under review" %}
							{% elif c.contribution.status == 3 %}
								{% trans "Approved" %}
							{% elif c.contribution.status == 4 %}
								{% trans "Rejected" %}
							{% elif c.contribution.status == 5 %}
								{% trans "Published" %}
							{% endif %}
						</td>
					</tr>
		{% if forloop.last %}
				</tbody>
			</table>
		{% endif %}
	{% endfor %}
	{% for r in review_requests %}
		{% if forloop.first %}
			<div class="page-title-2">{% trans "Review requests" %}</div>
			<table class="table table-hover table-striped">
				<thead>
				<tr>
					<th>{% trans "Review Id"  %}</th>
					<th>{% trans "Editor" %}</th>
					<th>{% trans "Status" %}</th>
				</tr>
				</thead>
				<tbody>
		{% endif %}
					<tr class='clickable-row' data-href="{% url 'contribute:review' review_request_id=r.pk %}">
						<td>
						{{ r.pk }}
						<td>{{ r.editor }}</td>
						<td>
							{% if r.response == 0 %}
								{% trans "Not replied" %}
							{% elif r.response == 1 %}
								{% trans "Accepted for review" %}
							{% endif %}
						</td>
					</tr>
		{% if forloop.last %}
				</tbody>
			</table>
		{% endif %}
	{% endfor %}
	</section>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $(".clickable-row").click(function() {
			window.document.location = $(this).data("href");
		});
	});
</script>
{% endblock %}