voyages/apps/contribute/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from voyages.apps.contribute import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^guidelines', TemplateView.as_view(template_name='contribute/guidelines.html'), name='guidelines'),

    url(r'^thanks', TemplateView.as_view(template_name='contribute/thanks.html'), name='thanks'),
    
    url(r'^delete_voyage', views.delete, name='delete_voyage'),

    url(r'^delete_review/(?P<contribution_id>\d+)', views.delete_review, name='delete_review'),

    url(r'^places_ajax', views.get_places, name='places_ajax'),

    url(r'^voyage_ajax', views.get_voyage_by_id, name='voyage_ajax'),
    
    url(r'^interim/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)/save_ajax$',
        views.interim_save_ajax, name='interim_save_ajax'),

    url(r'interim/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)',
        views.interim, name='interim'),

    url(r'interim_commit/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)',
        views.interim_commit, name='interim_commit'),

    url(r'interim_summary/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)$',
        views.interim_summary, name='interim_summary'),

    url(r'interim_summary/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)/(?P<mode>reviewer)$',
        views.interim_summary, name='interim_summary_reviewer'),

    url(r'interim_summary/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)/(?P<mode>editor)$',
        views.interim_summary, name='interim_summary_editor'),
        
    url(r'legal', views.legal, name='legal'),

    url(r'edit_voyage', views.edit, name='edit_voyage'),

    url(r'merge_voyages', views.merge, name='merge_voyages'),

    url(r'new_voyage', views.new_voyage, name='new_voyage'),

    url(r'editor_main', views.editor_main, name='editor_main'),

    url(r'review_request/(?P<review_request_id>\d+)',
        views.review_request, name='review_request'),
    url(r'reply_review_request', views.reply_review_request, name='reply_review_request'),
    
    url(r'editorial_review/(?P<editor_contribution_id>\d+)/save_ajax', views.editorial_review_interim_save_ajax, name='editorial_review_interim_save_ajax'),
    url(r'editorial_review/(?P<editor_contribution_id>\d+)/submit_editorial_decision', views.submit_editorial_decision, name='submit_editorial_decision'),
    url(r'editorial_review/(?P<review_request_id>\d+)', views.editorial_review, name='editorial_review'),
    
    url(r'editorial_sources', views.editorial_sources, name='editorial_sources'),
    
    url(r'begin_editorial_review', views.begin_editorial_review, name='begin_editorial_review'),
        
    url(r'review/(?P<reviewer_contribution_id>\d+)/save_ajax', views.review_interim_save_ajax, name='review_interim_save_ajax'),
    url(r'review/(?P<review_request_id>\d+)/submit_review_to_editor', views.submit_review_to_editor, name='submit_review_to_editor'),
    url(r'review/(?P<review_request_id>\d+)', views.review, name='review'),

    url(r'json_pending_requests', views.get_pending_requests, name='json_pending_requests'),
    url(r'json_pending_publication', views.get_pending_publication, name='json_pending_publication'),
    url(r'json_reviewers', views.get_reviewers, name='json_reviewers'),
    url(r'json_publish_pending', views.publish_pending, name='json_publish_pending'),
    url(r'json_retrieve_publication_status', views.retrieve_publication_status, name='json_retrieve_publication_status'),
    url(r'download_voyages_status', views.download_voyages_status, name='download_voyages_status'),
    url(r'download_voyages_go', views.download_voyages_go, name='download_voyages_go'),
    url(r'download_voyages', views.download_voyages, name='download_voyages'),
    
    url(r'post_review_request', views.post_review_request, name='post_review_request'),
    url(r'post_archive_review_request', views.post_archive_review_request, name='post_archive_review_request'),
    
    url(r'impute_contribution/(?P<editor_contribution_id>\d+)', views.impute_contribution, name='impute_contribution'),
    ]

voyages/apps/past/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

import voyages.apps.static_content.views
import voyages.apps.past.views

urlpatterns = [
    url(r'^api/search', voyages.apps.past.views.search_enslaved, name='search'),
    url(r'^api/modern-countries', voyages.apps.past.views.get_modern_countries, name='modern-countries'),
    url(r'^api/language-groups', voyages.apps.past.views.get_language_groups, name='language-groups'),
    url(r'^api/ethnicities', voyages.apps.past.views.get_ethnicities, name='ethnicities'),
    url(r'^database', TemplateView.as_view(template_name='past/database.html'), name='database'),
    url(r'^contribute/(?P<id>.*)', TemplateView.as_view(template_name='past/contribute.html'), name='contribute'),
    url(r'^enslaved_contribution', voyages.apps.past.views.enslaved_contribution),
    url(r'^store-audio/(?P<contrib_pk>[0-9]+)/(?P<name_pk>[0-9]+)/(?P<token>.*)', voyages.apps.past.views.store_audio)
    ]

voyages/apps/resources/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

import voyages.apps.static_content.views
import voyages.apps.resources.views

urlpatterns = [
    url(r'^$', voyages.apps.static_content.views.get_static_content, {'group': 'Resources'},
        name='index'),
    url(r'^about', TemplateView.as_view(template_name='resources/about.html'), name='about'),
    url(r'^downloads', TemplateView.as_view(template_name='resources/downloads.html'), name='downloads'),
    url(r'^lessons', TemplateView.as_view(template_name='resources/lessons.html'), name='lessons'),
    url(r'^links', TemplateView.as_view(template_name='resources/links.html'), name='links'),

    #handle all cases for now
    url(r'^images/category/(?P<category>\w+)/(?P<page>\d{1,3})/detail',
        voyages.apps.resources.views.get_image_detail,
        name='image-detail'),
    url(r'^images/category/(?P<category>\w+)/(?P<page>\d{1,3})',
        voyages.apps.resources.views.get_images_category_detail,
        name='images-category-detail'),
    url(r'^images/category/(?P<category>\w+)',
        voyages.apps.resources.views.get_images_category,
        name='images-category'),
    url(r'^images/search/(?P<page>\d{1,3})/detail',
        voyages.apps.resources.views.get_image_search_detail,
        name='image-search-detail-window'),
    url(r'^images/search/(?P<page>\d{1,3})',
        voyages.apps.resources.views.images_search_detail,
        name='images-search-detail'),
    url(r'^images/search',
        voyages.apps.resources.views.images_search,
        name='images-search'),
    url(r'^images/', voyages.apps.resources.views.get_all_images,
        name='images'),
    url(r'^names-database',
        voyages.apps.resources.views.get_all_slaves,
        name='origins')]

voyages/urls.py
from django.conf import settings
from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
from autocomplete_light import shortcuts as autocomplete_light
autocomplete_light.autodiscover()
from django.contrib import admin

admin.autodiscover()

# Sitemap
from sitemap import StaticSitemap

js_info_dict = {
    'packages': ('voyages',),
}

import voyages.apps.assessment.views
import voyages.apps.voyage.views
import voyages.apps.common.views
import voyages.apps.past.views
import django.contrib.sitemaps.views
import django.views.i18n
import django.views.static

urlpatterns = [
    url(r'^', include('voyages.apps.static_content.urls', namespace='static_content')),
    # Short permalink
    url(r'^estimates/(?P<link_id>\w+)', voyages.apps.assessment.views.restore_permalink, name='restore_e_permalink'),
    url(r'^voyages/(?P<link_id>\w+)', voyages.apps.voyage.views.restore_permalink, name='restore_v_permalink'),
    url(r'^past-db/(?P<link_id>\w+)', voyages.apps.past.views.restore_permalink, name='restore_past_permalink'),

    #Include url handlers of each section
    url(r'^voyage/', include('voyages.apps.voyage.urls', namespace='voyage')),
    url(r'^american/', include('voyages.apps.american.urls', namespace='american')),
    url(r'^assessment/', include('voyages.apps.assessment.urls', namespace='assessment')),
    url(r'^about/', include('voyages.apps.about.urls', namespace='about')),
    url(r'^common/', include('voyages.apps.common.urls', namespace='common')),
    url(r'^past/', include('voyages.apps.past.urls', namespace='past')),
    url(r'^resources/', include('voyages.apps.resources.urls', namespace='resources')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^contribute/', include('voyages.apps.contribute.urls', namespace='contribute')),
    url(r'^search/', include('haystack.urls', namespace='search')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),

    # Handle language changes
    url(r'^setlanguage/(?P<lang_code>\w+)', voyages.apps.common.views.set_language, name='set_lang'),

    # Translation support for javascript code.
    url(r'^jsi18n/', django.views.i18n.javascript_catalog, js_info_dict, name='javascript-catalog'),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^captcha/', include('captcha.urls'))]

# XML generated sitemap
sitemaps = {
    'staticpages': StaticSitemap(urlpatterns),
}
# URLs not included in the sitemap
urlpatterns += [
    url(r'^sitemap\.xml', django.contrib.sitemaps.views.sitemap, {'sitemaps': sitemaps}, name='sitemap-xml'),

    # Flatpages
    url(r'^pages/', include('django.contrib.flatpages.urls')),

    # Adding download files
    url(r'^admin/downloads', voyages.apps.voyage.views.download_file, name="downloads"),

    # Admin documentation
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Admin management
    url(r'^admin/', include(admin.site.urls))]

#Serving static files including files uploaded by users
if settings.DEBUG:
# static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^documents/(?P<path>.*)', django.views.static.serve, {
        'document_root': settings.MEDIA_ROOT})]

voyages/apps/past/templates/past/_actions.html
{% load i18n %}

<!-- Actions -->
<li class="nav-item dropdown nav-item-compact" v-if="activated">
  <a class="nav-link" data-toggle="collapse" href="#panelCollapse" role="button" aria-expanded="false" aria-controls="panelCollapse">
    <div class="btn-navbar">
      <i class="fa fa-filter"></i>
      {% trans 'View all' %}
    </div>
  </a>
</li>

<li class="nav-item dropdown nav-item-compact" v-if="activated">
  <a class="nav-link" @click="resetAll" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
    <div class="btn-navbar">
      <i class="fa fa-times"></i>
      {% trans 'Reset all' %}
    </div>
  </a>
</li>
<!-- Actions -->

voyages/apps/past/templates/past/_african-name.html
{% load i18n %}

<li class="nav-item dropdown">
  <v-menu-title :count="filter.africanName.count" title="{% trans 'African Name' %}"></v-menu-title>

  <v-panel-singular @apply="apply" @reset="reset" group="africanName" title="{% trans 'Name' %}" sub-group="name" :filters="filter.africanName.name" align="left">
    <div slot="v-panel-header">
      <v-panel-header title="{% trans 'Name' %}" description="{% trans 'Possible modern counterpart' %}">
        <div slot="v-modal-content"></div>
      </v-panel-header>
    </div>

    <div slot="v-panel-content" slot-scope="scope">
      <v-number @change="changed"
        :filter="scope.filters.var_enslaved_id">
      </v-number>

      <v-text @change="changed"
        :filter="scope.filters.var_searched_name"
      ></v-text>

      <v-toggle @change="changed"
        :filter="scope.filters.var_exact_name_search">
      </v-toggle>
    </div>
  </v-panel-singular>
</li>

voyages/apps/past/templates/past/_cultural-association.html
{% load i18n %}

<li class="nav-item dropdown">
  <v-menu-title :count="filter.culturalAssociation.count" title="{% trans 'Cultural Association' %}"></v-menu-title>

  <v-panel-singular @apply="apply" @reset="reset" group="culturalAssociation" title="{% trans 'Personal Data' %}" sub-group="culturalAssociation"
    :filters="filter.culturalAssociation.culturalAssociation" align="left">
    <div slot="v-panel-header">
      <v-panel-header title="{% trans 'Cultural Association' %}" description="{% trans 'Description' %}">
        <div slot="v-modal-content"></div>
      </v-panel-header>
    </div>

    <div slot="v-panel-content" slot-scope="scope">
      <!-- <v-treeselect
        :filter="scope.filters.var_register_country"
        @change="changed">
      </v-treeselect> -->

      <v-treeselect
        :filter="scope.filters.var_modern_country"
        @change="changed">
      </v-treeselect>

      <!-- <v-treeselect
        :filter="scope.filters.var_ethnicity"
        @change="changed">
      </v-treeselect> -->

      <v-treeselect
        :filter="scope.filters.var_language_groups"
        @change="changed">
      </v-treeselect>
    </div>
  </v-panel-singular>
</li>

voyages/apps/past/templates/past/_fate.html
{% load i18n %}

<li class="nav-item dropdown">
  <v-menu-title :count="filter.fate.count" title="{% trans 'Fate' %}"></v-menu-title>

  <v-panel-singular @apply="apply" @reset="reset" group="fate" title="{% trans 'Fate' %}" sub-group="fate" :filters="filter.fate.fate" align="left">
    <div slot="v-panel-header">
      <span class="badge badge-pill badge-secondary tooltip-pointer" data-toggle="tooltip" data-placement="top" title="To be implemented."> TO-DO </span>
      <v-panel-header title="{% trans 'Post Disembarkation Location' %}" description="{% trans 'Description' %}">
        <div slot="v-modal-content"></div>
      </v-panel-header>
    </div>

    <div slot="v-panel-content" slot-scope="scope">
      <v-treeselect
        :filter="scope.filters.var_post_disembarkation_location"
        @change="changed">
      </v-treeselect>
    </div>
  </v-panel-singular>
</li>

voyages/apps/past/templates/past/_itinerary.html
{% load i18n %}

<li class="nav-item dropdown">
  <v-menu-title :count="filter.itinerary.count" title="{% trans 'Itinerary' %}"></v-menu-title>

  <v-panel-singular @apply="apply" @reset="reset" group="itinerary" title="{% trans 'Personal Data' %}" sub-group="itinerary"
    :filters="filter.itinerary.itinerary" align="left">
    <div slot="v-panel-header">
      <v-panel-header title="{% trans 'Itinerary' %}" description="{% trans 'Description' %}">
        <div slot="v-modal-content"></div>
      </v-panel-header>
    </div>

    <div slot="v-panel-content" slot-scope="scope">
      <v-number @change="changed"
        :filter="scope.filters.var_voyage_id">
      </v-number>

      <v-text @change="changed"
        :filter="scope.filters.var_ship_name"
      ></v-text>

      <v-treeselect
        :filter="scope.filters.var_embarkation_ports"
        @change="changed">
      </v-treeselect>

      <v-treeselect
        :filter="scope.filters.var_disembarkation_ports"
        @change="changed">
      </v-treeselect>

      <!-- <v-text @change="changed"
        :filter="scope.filters.var_geocode"
      ></v-text> -->

      <v-number
        :filter="scope.filters.var_year_range"
        @change="changed">
      </v-number>

      <v-treeselect
        :filter="scope.filters.var_intended_disembarkation_port"
        @change="changed">
      </v-treeselect>
    </div>
  </v-panel-singular>
</li>

voyages/apps/past/templates/past/_panel.html
{% load i18n %}

{% verbatim %}
<div class="collapse" id="panelCollapse">
  <div class="panel-list" v-if="hasCurrentQuery">
    <span class="panel-list-item-wrapper">
      <span class="panel-list-item" v-for="variable in currentQuery">
        <span class="text-bold panel-variable-label">{{variable.label}}</span>
        <span class="panel-variable-op">{{variable.op | opLabelize}}</span>
        <span class="panel-variable-value" v-if="variable.searchTerm">{{variable.searchTerm | termLabelize}}.</span>
        <span v-else>
          <span class="panel-variable-value">{{variable.searchTerm0 | termLabelize}}<span v-if="!variable.searchTerm1">.</span></span>
          <span v-if="variable.searchTerm1">
            {% endverbatim %} and {% verbatim %}
            <span class="panel-variable-value">{{variable.searchTerm1 | termLabelize}}.</span>
          </span>
        </span>
      </span>
    </span>
    <a data-toggle="collapse" href="#panelCollapse" role="button" aria-expanded="true" aria-controls="panelCollapse">
      <div class="btn-panel"><i class="fa fa-times-circle"></i> {% endverbatim %} {% trans 'Hide' %} {% verbatim %}</div>
    </a>
  </div>
  <div class="panel-list" v-else>
    <div class="text-bold panel-variable-label">{% endverbatim %} {% trans 'No variables are selected' %} {% verbatim %}</div>
    <a data-toggle="collapse" href="#panelCollapse" role="button" aria-expanded="true" aria-controls="panelCollapse">
      <div class="btn-panel"><i class="fa fa-times-circle"></i> {% endverbatim %} {% trans 'Hide' %} {% verbatim %}</div>
    </a>
  </div>
</div>
{% endverbatim %}

voyages/apps/past/templates/past/_personal-data.html
{% load i18n %}

<li class="nav-item dropdown">
  <v-menu-title :count="filter.personalData.count" title="{% trans 'Personal Data' %}"></v-menu-title>

  <v-panel-singular @apply="apply" @reset="reset" group="personalData" title="{% trans 'Personal Data' %}" sub-group="personalData"
    :filters="filter.personalData.personalData" align="left">
    <div slot="v-panel-header">
      <v-panel-header title="{% trans 'Personal Data' %}" description="{% trans 'Description' %}">
        <div slot="v-modal-content"></div>
      </v-panel-header>
    </div>

    <div slot="v-panel-content" slot-scope="scope">
      <v-treeselect
        :filter="scope.filters.var_age_gender"
        @change="changed">
      </v-treeselect>

      <v-number @change="changed"
        :filter="scope.filters.var_age_range">
      </v-number>

      <v-number @change="changed"
        :filter="scope.filters.var_height_range">
      </v-number>
    </div>
  </v-panel-singular>
</li>

voyages/apps/past/templates/past/_sources.html
{% load i18n %}

<li class="nav-item dropdown">
  <v-menu-title :count="filter.sources.count" title="{% trans 'Sources' %}"></v-menu-title>

  <v-panel-singular @apply="apply" @reset="reset" group="sources" title="{% trans 'Sources' %}" sub-group="sources" :filters="filter.sources.sources" align="left">
    <div slot="v-panel-header">
      <span class="badge badge-pill badge-secondary tooltip-pointer" data-toggle="tooltip" data-placement="top" title="To be implemented."> TO-DO </span>
      <v-panel-header title="{% trans 'Sources' %}" description="{% trans 'Description' %}">
        <div slot="v-modal-content"></div>
      </v-panel-header>
    </div>

    <div slot="v-panel-content" slot-scope="scope">
      <v-text @change="changed"
        :filter="scope.filters.var_source"
      ></v-text>
    </div>
  </v-panel-singular>
</li>

voyages/apps/past/templates/past/_tabs.html
{% load i18n %}

<!-- Tabs -->
<ul class="nav nav-tabs trans-tab">
  <li class="nav-item">
    <a class="nav-link active" @click="setActive('results')" href="#results" data-toggle="tab" data-target="#results">{% trans 'Results' %}</a>
  </li>
</ul>
<!-- End of Tabs -->

<!-- TabContainers -->
<div id="tabsJustifiedContent" class="tab-content">
  <div id="results" class="tab-pane fade active show">
    <table id="results_main_table" class="table table-striped table-bordered"></table>

	{% include "database/_full_details_modal.html" %}
  </div>
</div>
<!-- End of TabContainers -->

voyages/apps/past/templates/past/contribute.html
{% extends "_base.html" %} {% load sass_tags %} {% load compress %}

{% load i18n %}
{% block csslist %}
    {% compress css %}
    <link href="{% sass_src 'scss/navbar-site.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'scss/main.scss' %}" rel="stylesheet" type="text/css" />
    {% endcompress %}
    <link href="{% sass_src 'scss/past_contribute.scss' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}maps/css/leaflet.css" />
    {% compress css %}
    <link href="{% sass_src 'scss/off-canvas.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'scss/search-ui.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'scss/v-component.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'scss/trans-search.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'scss/animations.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'scss/sidebar.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'scss/library/loading.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'scss/library/vue-treeselect@0.0.37.min.css' %}" rel="stylesheet" type="text/css" />
    {% endcompress %}
{% endblock %}

{% block title %}
    {% trans 'People of Atlantic Slave Trade - Database of the Enslavers' %}
{% endblock %}

{% block content %}
<div id="past-contribute" v-cloak>
    <div class="nav-header">
      <div>{% trans "People of Atlantic Slave Trade - Database of the Enslaved" %}</div>
      <div class="navbar-subtitle flex">
        <div class="navbar-subitem">
          <a data-toggle="collapse" href="{% url 'past:database' %}" role="button" aria-expanded="false" aria-controls="panelCollapse">
            <div class="btn-navbar">
              <i class="fas fa-arrow-circle-left"></i>
              {% trans 'Back to Search' %}
            </div>
          </a>
        </div>
        <div class="navbar-subitem">
          {% trans 'Contribute to origins of the name of this person' %}
        </div>

      </div>
    </div>

    <form id="form" name="form" method="post" action="{% url 'resources:origins' %}"
      enctype="application/x-www-form-urlencoded" >{% csrf_token %}
        <div class="container-new">
            <div class="row row-offcanvas row-offcanvas-right">
                <div class='col-md-4 col-xs-12 col-lg-3 sidebar-offcanvas' id="sidebar">
                    {% include "past-contribute/_left-menu.html" %}
                </div>
                <div class="col-md-8 col-xs-12 col-lg-9 pl-5">
                    <div class="row">
                      <div>
                        <ul class="nav nav-pills mb-3 contribute-navbar" id="pills-tab" role="tablist">
                            <li class="nav-item">
                                <span class="navbar-text font-weight-bold text-secondary" >{% trans 'Select to contribute' %}:</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">{% trans 'Names & Pronunciation' %}<span v-if="total_names > 0"> ([[ total_names ]])</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">{% trans 'Ethnics and Language Groups' %}</a>
                            </li>
                        </ul>
                      </div>
                    </div>
                    <div class="row">
                      <form>
                        <div class="tab-content container-fluid p-0" id="pills-tabContent">
                          {% include "past-contribute/_name_pronunciation.html" %}
                          {% include "past-contribute/_ethnics_language_group.html" %}
                        </div>
                      </form>
                    </div>
                  </div>
            </div>
    </form>
    {% include "past-contribute/_full_details_modal.html" %}
</div>

<script>
    var AFRICAN_ID = {{ id }};
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });
</script>

{% endblock %}

{% block footer %}
{% endblock %}


{% block jslist %}

{% include '_scripts.html' %}

<!-- Highcharts -->
{% compress js %}

<script src="{{ STATIC_URL }}scripts/library/vue-treeselect@0.0.37.min.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/library/string-utils.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/library/jquery.qtip@2.1.1.min.js" type="text/javascript" ></script>
<script src="{{ STATIC_URL }}scripts/library/menu-aim.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/library/vue-clipboard2.min.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/library/uuidv4@8.3.2.min.js" type="text/javascript"></script>

<script src="{{ STATIC_URL }}maps/js/leaflet.js"></script>
<script src="{{ STATIC_URL }}scripts/vue/includes/animation.js"></script>
<script src="{{ STATIC_URL }}scripts/vue/includes/build-request-body.js"></script>

<script src="{{ STATIC_URL }}scripts/vue/variables/constructors.js"></script>
<script src="{{ STATIC_URL }}scripts/vue/includes/menu-aim.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/vue/includes/sidebar.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/vue/includes/search_term.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/vue/includes/form-data.js" type="text/javascript"></script>


{% endcompress %}

<!-- vue components -->
<script src="{{ STATIC_URL }}scripts/vue/components/v-treeselect.js"></script>
<script src="{{ STATIC_URL }}scripts/vue/components/v-toggle.js"></script>
<!-- vue components -->

<script src="{{ STATIC_URL }}scripts/vue/past/includes/helpers.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/vue/past-contribute/app.js" type="text/javascript"></script>

{% endblock %}