voyages/apps/about/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

import voyages.apps.static_content.views
import voyages.apps.about.views

urlpatterns = [
    url(r'^about', TemplateView.as_view(template_name='index.html'), name='about'),
]

voyages/apps/assessment/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

import voyages.apps.assessment.views
import voyages.apps.static_content.views

urlpatterns = [
    url(r'^c(?P<chapternum>\d{2})_s(?P<sectionnum>\d{2})_p(?P<pagenum>\d{2})$',
        voyages.apps.assessment.views.get_page, name='get-page'),
    url(r'^$', voyages.apps.static_content.views.get_static_content, {'group': 'Assessment'}, name='index'),
    
    url(r'^estimates', voyages.apps.assessment.views.get_estimates, name='estimates'),

    url(r'^permalink', voyages.apps.assessment.views.get_permanent_link, name='permanent-link')]

voyages/apps/common/urls.py
from django.conf.urls import url    
from voyages.apps.common.views import *

urlpatterns = [
    url(r'^getflatpage(?P<url>.+)', get_flat_page_content, name='get_flat_page_content'),
    url(r'^flatpagehierarchy(?P<prefix>.+)', get_flat_page_hierarchy, name='get_flat_page_hierarchy'),
    url(r'nations', get_nations, name='get_nations')
]

voyages/apps/past/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

import voyages.apps.static_content.views
import voyages.apps.past.views

urlpatterns = [
    url(r'^api/search', voyages.apps.past.views.search_enslaved, name='search'),
    url(r'^api/modern-countries', voyages.apps.past.views.get_modern_countries, name='modern-countries'),
    url(r'^api/language-groups', voyages.apps.past.views.get_language_groups, name='language-groups'),
    url(r'^api/ethnicities', voyages.apps.past.views.get_ethnicities, name='ethnicities'),
    url(r'^database', TemplateView.as_view(template_name='past/database.html'), name='database'),
    url(r'^contribute/(?P<id>.*)', TemplateView.as_view(template_name='past/contribute.html'), name='contribute'),
    url(r'^enslaved_contribution', voyages.apps.past.views.enslaved_contribution),
    url(r'^store-audio/(?P<contrib_pk>[0-9]+)/(?P<name_pk>[0-9]+)/(?P<token>.*)', voyages.apps.past.views.store_audio)
    ]

voyages/apps/resources/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

import voyages.apps.static_content.views
import voyages.apps.resources.views

urlpatterns = [
    url(r'^$', voyages.apps.static_content.views.get_static_content, {'group': 'Resources'},
        name='index'),
    url(r'^about', TemplateView.as_view(template_name='resources/about.html'), name='about'),
    url(r'^downloads', TemplateView.as_view(template_name='resources/downloads.html'), name='downloads'),
    url(r'^lessons', TemplateView.as_view(template_name='resources/lessons.html'), name='lessons'),
    url(r'^links', TemplateView.as_view(template_name='resources/links.html'), name='links'),

    #handle all cases for now
    url(r'^images/category/(?P<category>\w+)/(?P<page>\d{1,3})/detail',
        voyages.apps.resources.views.get_image_detail,
        name='image-detail'),
    url(r'^images/category/(?P<category>\w+)/(?P<page>\d{1,3})',
        voyages.apps.resources.views.get_images_category_detail,
        name='images-category-detail'),
    url(r'^images/category/(?P<category>\w+)',
        voyages.apps.resources.views.get_images_category,
        name='images-category'),
    url(r'^images/search/(?P<page>\d{1,3})/detail',
        voyages.apps.resources.views.get_image_search_detail,
        name='image-search-detail-window'),
    url(r'^images/search/(?P<page>\d{1,3})',
        voyages.apps.resources.views.images_search_detail,
        name='images-search-detail'),
    url(r'^images/search',
        voyages.apps.resources.views.images_search,
        name='images-search'),
    url(r'^images/', voyages.apps.resources.views.get_all_images,
        name='images'),
    url(r'^names-database',
        voyages.apps.resources.views.get_all_slaves,
        name='origins')]

voyages/apps/voyage/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView

import voyages.apps.voyage.views
import voyages.apps.voyage.search_views
import voyages.apps.static_content.views

urlpatterns = [

    # flatpages
    url(r'^about', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^essays', TemplateView.as_view(template_name='essays.html'), name='essays'),
    url(r'^downloads', TemplateView.as_view(template_name='downloads.html'), name='downloads'),
    url(r'^maps', TemplateView.as_view(template_name='maps.html'), name='maps'),
    url(r'^ship', TemplateView.as_view(template_name='ship.html'), name='ship'),

    url(r'^c(?P<chapternum>\w{2})_s(?P<sectionnum>\w{2})_p(?P<pagenum>\w{2})',
        voyages.apps.voyage.views.get_page, name='get-page'),
    url(r'^$', voyages.apps.static_content.views.get_static_content, {'group': 'Voyage'}, name='index'),

    #url(r'^c01_s03_cover', voyages.apps.voyage.views.variable_list, name='variables'),
    url(r'^reload-cache', voyages.apps.voyage.views.reload_cache, name='reload_cache'),

    url(r'^permalink', voyages.apps.voyage.views.get_permanent_link, name='permanent-link'),
    url(r'^contribute', RedirectView.as_view(url='/contribute'), name='submission-login'),

    url(r'^(?P<voyage_id>[0-9]+)/variables', voyages.apps.voyage.views.voyage_variables, name='voyage_variables'),
    url(r'^(?P<voyage_id>[0-9]+)/map', voyages.apps.voyage.views.voyage_map, name='voyage_map'),
    url(r'^(?P<voyage_id>[0-9]+)/images', voyages.apps.voyage.views.voyage_images, name='voyage_images'),

    url(r'^csv_stats_download', voyages.apps.voyage.views.csv_stats_download, name='csv_stats_download'),
    url(r'^database', TemplateView.as_view(template_name='database.html'), name='database'),
    url(r'var-options', voyages.apps.voyage.search_views.get_var_options, name='var-options'),
    url(r'filtered-places', voyages.apps.voyage.search_views.get_filtered_places, name='filtered-places'),
    url(r'save-query', voyages.apps.voyage.search_views.save_query, name='save-query'),
    url(r'get-saved-query/(?P<query_id>\w+)', voyages.apps.voyage.search_views.get_saved_query, name='get-saved-query'),
    url(r'^api/search', voyages.apps.voyage.search_views.ajax_search, name='search'),
    url(r'^api/download', voyages.apps.voyage.search_views.ajax_download, name='download'),
    url(r'get-all-sources', voyages.apps.voyage.search_views.get_all_sources, name='all-sources'),
    url(r'get-timelapse-regions', voyages.apps.voyage.search_views.get_timelapse_port_regions, name='get-timelapse-regions'),
    url(r'get-compiled-routes', voyages.apps.voyage.search_views.get_compiled_routes, name='get-compiled-routes')
]

voyages/urls.py
from django.conf import settings
from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
from autocomplete_light import shortcuts as autocomplete_light
autocomplete_light.autodiscover()
from django.contrib import admin

admin.autodiscover()

# Sitemap
from sitemap import StaticSitemap

js_info_dict = {
    'packages': ('voyages',),
}

import voyages.apps.assessment.views
import voyages.apps.voyage.views
import voyages.apps.common.views
import voyages.apps.past.views
import django.contrib.sitemaps.views
import django.views.i18n
import django.views.static

urlpatterns = [
    url(r'^', include('voyages.apps.static_content.urls', namespace='static_content')),
    # Short permalink
    url(r'^estimates/(?P<link_id>\w+)', voyages.apps.assessment.views.restore_permalink, name='restore_e_permalink'),
    url(r'^voyages/(?P<link_id>\w+)', voyages.apps.voyage.views.restore_permalink, name='restore_v_permalink'),
    url(r'^past-db/(?P<link_id>\w+)', voyages.apps.past.views.restore_permalink, name='restore_past_permalink'),

    #Include url handlers of each section
    url(r'^voyage/', include('voyages.apps.voyage.urls', namespace='voyage')),
    url(r'^american/', include('voyages.apps.american.urls', namespace='american')),
    url(r'^assessment/', include('voyages.apps.assessment.urls', namespace='assessment')),
    url(r'^about/', include('voyages.apps.about.urls', namespace='about')),
    url(r'^common/', include('voyages.apps.common.urls', namespace='common')),
    url(r'^past/', include('voyages.apps.past.urls', namespace='past')),
    url(r'^resources/', include('voyages.apps.resources.urls', namespace='resources')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^contribute/', include('voyages.apps.contribute.urls', namespace='contribute')),
    url(r'^search/', include('haystack.urls', namespace='search')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),

    # Handle language changes
    url(r'^setlanguage/(?P<lang_code>\w+)', voyages.apps.common.views.set_language, name='set_lang'),

    # Translation support for javascript code.
    url(r'^jsi18n/', django.views.i18n.javascript_catalog, js_info_dict, name='javascript-catalog'),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^captcha/', include('captcha.urls'))]

# XML generated sitemap
sitemaps = {
    'staticpages': StaticSitemap(urlpatterns),
}
# URLs not included in the sitemap
urlpatterns += [
    url(r'^sitemap\.xml', django.contrib.sitemaps.views.sitemap, {'sitemaps': sitemaps}, name='sitemap-xml'),

    # Flatpages
    url(r'^pages/', include('django.contrib.flatpages.urls')),

    # Adding download files
    url(r'^admin/downloads', voyages.apps.voyage.views.download_file, name="downloads"),

    # Admin documentation
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Admin management
    url(r'^admin/', include(admin.site.urls))]

#Serving static files including files uploaded by users
if settings.DEBUG:
# static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^documents/(?P<path>.*)', django.views.static.serve, {
        'document_root': settings.MEDIA_ROOT})]

voyages/apps/american/models.py
from django.db import models

# Create your models here.

voyages/apps/static_content/models.py
from django.db import models


class ContentGroup(models.Model):
    """
    Model stores static content groups.
    """

    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Static content group"
        verbose_name_plural = "Static content groups"

    def __unicode__(self):
        return self.name


class ContentPage(models.Model):
    """
    Model stores static content pages.
    """

    title = models.TextField(max_length=50)
    description = models.TextField(max_length=2000)
    order = models.IntegerField()
    group = models.ForeignKey(ContentGroup)

    class Meta:
        verbose_name = "Static content page"
        verbose_name_plural = "Static content pages"

    def __unicode__(self):
        return self.title

voyages/apps/assessment/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import *
import globals


class EstimateSelectionForm(forms.Form):
    lambda_fun = lambda x: (str(x[0]), x[1][0])

    row_choices = map(lambda_fun, enumerate(globals.table_rows))
    rows = forms.ChoiceField(label=_('Rows'), choices=row_choices, initial=[row_choices[0][1]])
    rows.initial = row_choices[0][0]

    col_choices = map(lambda_fun, enumerate(globals.table_columns))
    columns = forms.ChoiceField(label=_('Columns'), choices=col_choices, initial=[col_choices[1][1]])
    columns.initial = col_choices[1][0]

    cell_choices = map(lambda_fun, enumerate(globals.table_cells))
    cells = forms.ChoiceField(label=_('Cells'), choices=cell_choices, initial=[cell_choices[1][1]])
    cells.initial = cell_choices[1][0]
    include_empty = forms.BooleanField(label=_('Include empty'), required=False, initial=False)


class EstimateYearForm(forms.Form):
    frame_from_year = forms.IntegerField(label=_('From'), widget=forms.TextInput(
        attrs={'class': "short_field_white"}))
    frame_to_year = forms.IntegerField(label=_('To'), widget=forms.TextInput(
        attrs={'class': "short_field_white"}))

voyages/apps/resources/forms.py
from django import forms
from .models import *


class ImageAdminForm(forms.ModelForm):
    """
    Form for editing HTML for FAQ answer
    """
    description = forms.CharField(widget=forms.Textarea(attrs={'rows':6, 'cols':60}))

    class Meta:
        model = Image
        fields = '__all__'


class ResultsPerPageOptionForm(forms.Form):
    choices = (('1', 10), ('2', 20), ('3', 50), ('4', 100), ('5', 200))
    option = forms.ChoiceField(widget=forms.Select(attrs={'onchange': 'this.form.submit();'}), choices=choices,
                               initial='2')

    def cleaned_option(self):
        try:
            option_value = self.cleaned_data['option']
        except:
            option_value = '2'

        return dict(self.fields['option'].choices)[option_value]

voyages/apps/about/views.py
from voyages.apps.common.views import render_locale_flatpage

# A catch all for URL matching
def render_about_flatpage(request, flatpage_url):
    flatpage_url = "/about/" + flatpage_url + "/"
    return render_locale_flatpage(request, 'about/flatpage.html', flatpage_url)

voyages/apps/american/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'database.html', {'mode' : 'intra'})

voyages/apps/static_content/views.py
from django.shortcuts import render
from .models import ContentPage

group_templates = {"Voyage": "voyages-index.html",
                   "Assessment": "assessment-index.html",
                   "Resources": "resources-index.html",
                   "About": "about-index.html"}


def get_static_content(request, group=None):
    """
    View to show appropriate landing page
    :param request: current request
    :param group: group (if empty, main landing page)
    :return: render
    """

    if group is None:
        # It's main landing page
        objects = ContentPage.objects.filter(group__name="Main").order_by('order')
        template = "static_content/index.html"
    else:
        objects = ContentPage.objects.filter(group__name=group).order_by('order')
        template = "static_content/" + group_templates[group]

    return render(request, template, {'objs': objects})

voyages/templates/base.html
{% load i18n %}
{% load sass_tags %}
{% load compress %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="description" content=" Drawing on extensive archival records, this digital memorial allows analysis of the ships, traders, and captives in the Atlantic slave trade. The three databases below provide details of 36,000 trans-Atlantic slave voyages, 10,000 intra-American ventures, names and personal information. You can read the introductory maps for a high-level guided explanation, view the timeline and chronology of the traffic, or watch the slave ship and slave trade animations to see the dispersal in action.">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="theme-color" content="#008ca8">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

	{% compress css %}
	<link href="{% sass_src 'scss/library/bootstrap@4.0.0.min.css' %}" rel="stylesheet" type="text/css" />
	<link href="{% sass_src 'scss/library/dataTables.boostrap4@1.10.16.min.css' %}" rel="stylesheet" type="text/css" />
	{% endcompress %}
	<script src="https://kit.fontawesome.com/2ebfe61a88.js"></script>
		
	{% block csslist %} {% endblock %}

	{% compress js %}
	<script src="{{ STATIC_URL }}scripts/library/jquery@3.3.1.min.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}scripts/library/modernizr@2.8.3.js" type="text/javascript"></script>
	{% endcompress %}

	<link rel="apple-touch-icon" sizes="180x180" href="{{ STATIC_URL }}images/site/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="{{ STATIC_URL }}images/site/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="{{ STATIC_URL }}images/site/favicon-16x16.png">
	<link rel="manifest" href="{{ STATIC_URL }}images/site/site.webmanifest">
	
	<title>{% block title %}{% trans 'Image Galleries' %}{% endblock %}</title>
</head>

<body>
	<div class="container-viewport">
		{% block top_bar %} {% include "topbar.html" %} {% endblock %}
		{% block additional_sec_bar %} {% endblock %} {% comment %} Secondary menu containing breadcrumb links and help links {% endcomment %}
		{% block content %}{% endblock %}
	</div>
	{% block footer %}{% endblock %}
	{% include "google-analytics.html" %}

	<!-- I18n of javascript text -->
	<script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>

	<!-- Use a global JS constant to specify the root of static urls -->
	<script language="javascript">var STATIC_URL = "{{ STATIC_URL|escapejs }}";</script>
	<script language="javascript">var LANGUAGE_CODE = "{{ LANGUAGE_CODE|escapejs }}";</script>

	{% compress js %}
	<script src="{{ STATIC_URL }}scripts/library/datatables.custom.min.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}scripts/library/popper@1.12.9.min.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}scripts/library/bootstrap@4.0.0.min.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}scripts/library/dataTables.bootstrap4@1.10.16.min.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}scripts/vue/includes/off-canvas.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}scripts/vue/includes/footer.js" type="text/javascript"></script>
	{% endcompress %}

	{% block jslist %} {% endblock %}
</body>

</html>

voyages/templates/footer.html
{% load i18n %}
{% comment %}Custom footer for the home page {% endcomment %}

<footer class="footer-flex-container" style=" ">
    <div class="footer-copyrights">
      <div class="copyright">
        <div class="highlight"><a href="/about/about/" target="_blank" rel="noopener" class="link grey"><span class="bold">Slave Voyages</span> v{{ RELEASE_VERSION }}</a></div>
        <div class="highlight">{% trans 'Copyright 2019 Emory University. Software licensed under' %} <a target="_blank" rel="noopener" href="https://www.gnu.org/licenses/gpl-3.0.en.html" class="grey"><span class="link">{% trans 'GNU General Public License 3.0' %}</span></a> {% trans 'or later version.' %}</div>
        <div class="highlight">{% trans 'Some content licensed under' %} <a target="_blank" rel="noopener"  href="https://creativecommons.org/licenses/by-nc/3.0/us/" class="grey"><span class="link">{% trans 'Creative Commons Attribution-Non-Commercial 3.0' %}</span></a>.</div>
      </div>
    </div>

    <div class="footer-logo">
      <a target="_blank" rel="noopener" href="http://digitalscholarship.emory.edu/" class="link">
        <img alt="Emory Center for Digital Scholarship" src="{{STATIC_URL}}images/site/landing/eu-lits.svg" style="height: 75px;">
      </a>
    </div>
</footer>

voyages/templates/google-analytics.html
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-6500832-2', 'auto');
ga('send', 'pageview');
</script>

voyages/templates/print.html
library/jquery@3.3.1.min.js<!DOCTYPE html>
<html lang="en">
    <head>
        <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    	<script src="{{ STATIC_URL }}scripts/library/jquery@3.3.1.min.js"></script>
    </head>
    <body>
        {% block center-content %}
        {% endblock %}
    </body>
</html>

voyages/templates/topbar.html
{% load i18n %}

<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
	<div class="nav-container">
		<!-- <a href="/" class="navbar-brand">Slave Voyages</a> -->
		<a href="/" class="navbar-brand" ><img src="{{STATIC_URL}}images/site/sv-logo.svg" alt="Slave Voyages" class="sv-logo"> </a>
		<button class="navbar-toggler float-right" aria-label="Navigation Toggle" type="button" data-toggle="collapse" data-target="#sv-navbar-collapse">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="navbar-collapse collapse" id="sv-navbar-collapse">
			<ul class="navbar-nav ml-auto" id="sv-navbar">
				<li class="nav-item dropdown" id="link-trans-atlantic">
					<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{% trans 'Trans-Atlantic' %}</a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="{% url 'voyage:about' %}">{% trans "Understanding the Database" %}</a>
						<a class="dropdown-item" href="{% url 'voyage:database' %}">{% trans "Database" %}</a>
						<a class="dropdown-item" href="{% url 'assessment:estimates' %}">{% trans "Estimates" %}</a>
						<a class="dropdown-item" href="{% url 'voyage:essays' %}">{% trans "Essays" %}</a>
						<a class="dropdown-item" href="{% url 'voyage:downloads' %}">{% trans "Downloads" %}</a>

						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'voyage:maps' %}">{% trans "Introductory Maps" %}</a>
						<a class="dropdown-item" href="{% url 'voyage:ship' %}">{% trans 'Slave Ship in 3D Video' %}</a>
						<a class="dropdown-item" href="{% url 'assessment:estimates' %}?selected_tab=timeline">{% trans 'Timeline and Chronology' %}</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'contribute:index' %}">{% trans "Contribute Data" %}</a>
					</div>
				</li>

				<li class="nav-item dropdown" id="link-american">
					<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" >{% trans 'Intra-American' %}</a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="{% url 'american:about' %}">{% trans "Understanding the Database" %}</a>
						<a class="dropdown-item" href="{% url 'american:database' %}">{% trans "Database" %}</a>
						<a class="dropdown-item" href="{% url 'american:essays' %}">{% trans "Essays" %}</a>
						<a class="dropdown-item" href="{% url 'american:downloads' %}">{% trans "Downloads" %}</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'contribute:index' %}">{% trans "Contribute Data" %}</a>
					</div>
				</li>

				<li class="nav-item dropdown" id="link-past">
					<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" >{% trans 'African Names' %}<!--People of the Atlantic Slave Trade--></a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="{% url 'resources:about' %}">Understanding the Database</a>
						<a class="dropdown-item" href="{% url 'resources:origins' %}">{% trans "Database" %}</a>
						<a class="dropdown-item" href="{% url 'resources:downloads' %}">{% trans "Downloads" %}</a>
					</div>
				</li>

				<li class="nav-item dropdown" id="link-resources">
					<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" >{% trans 'Resources' %}</a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="{% url 'resources:images' %}">{% trans "Image Galleries" %}</a>
						<a class="dropdown-item" href="{% url 'resources:lessons' %}">{% trans "Lesson Plans" %}</a>
						<a class="dropdown-item" href="{% url 'resources:links' %}">{% trans "External Links" %}</a>
					</div>
				</li>

				<li class="nav-item dropdown" id="link-about">
					<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" >{% trans 'About' %}</a>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="{% url 'about:about' %}">{% trans "About" %}</a>
						<a class="dropdown-item" href="/about/about#news/10/en/">{% trans "News" %}</a>
						<a class="dropdown-item" href="https://docs.google.com/forms/d/e/1FAIpQLSc2xoG0_OpkW--hZUXAvwTB6ZuNYDze1MDre1c5gyH0MrS8Jw/viewform" rel="noopener noreferrer" target="_blank">{% trans "Provide User Feedback" %}</a>
						<a class="dropdown-item" href="mailto:voyages@emory.edu?subject=Report an Issue"  rel="noopener noreferrer" target="_blank">{% trans "Report Issues" %}</a>
					</div>
				</li>

				{% get_current_language as LANGUAGE_CODE %}
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ LANGUAGE_CODE|upper }}</a>
					<div class="dropdown-menu dropdown-menu-right">

						{% for lang in LANGUAGES %}
							{% get_language_info for lang.0 as lang_info %}
							<a class="dropdown-item language_link language_link_{{ lang.0 }}" href="{% if lang.0 == LANGUAGE_CODE %}#{% else %}{% url 'set_lang' lang.0 %}{% endif %}">{{ lang_info.name_local|title }}</a>
						{% endfor %}
					</div>
				</li>

			</ul>
		</div>
	</div>
</nav>

<!--  Contains the navigation menu in a nested-unordered-list hierarchy
	- links are managed by the navigation_topbar.js menu -->

	<script type="text/javascript">
	// highlight the active link in the navigation bar
	var url = window.location.pathname;
	urlElements = url.split("/");
	if (urlElements[1] == "voyage" || urlElements[1] == "assessment") {
		document.getElementById("link-trans-atlantic").classList.add("active-link");
	} else if (urlElements[1] == "american") {
		document.getElementById("link-american").classList.add("active-link");
	} else if (urlElements[1] == "resources" && urlElements[2] == "about") {
		document.getElementById("link-past").classList.add("active-link");
	} else if ((urlElements[1] == "resources" && urlElements[2] == "names-database") || (urlElements[1] == "resources" && urlElements[2] == "downloads")) {
		document.getElementById("link-past").classList.add("active-link");
	} else if (urlElements[1] == "resources" || urlElements[1] == "education") {
		document.getElementById("link-resources").classList.add("active-link");
	} else if (urlElements[1] == "about" || urlElements[1] == "help") {
		document.getElementById("link-about").classList.add("active-link");
	}

	$(document).ready(function() {
		// reload the page after a language is switched
		$('.language_link').click(function(e) {
			e.preventDefault();
			$.ajax($(this).attr('href'))
				.done(function() {
					window.location.reload();
				});
		});
	});
	</script>