voyages/apps/about/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

import voyages.apps.static_content.views
import voyages.apps.about.views

urlpatterns = [
    url(r'^about', TemplateView.as_view(template_name='index.html'), name='about'),
]

voyages/apps/resources/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

import voyages.apps.static_content.views
import voyages.apps.resources.views

urlpatterns = [
    url(r'^$', voyages.apps.static_content.views.get_static_content, {'group': 'Resources'},
        name='index'),
    url(r'^about', TemplateView.as_view(template_name='resources/about.html'), name='about'),
    url(r'^downloads', TemplateView.as_view(template_name='resources/downloads.html'), name='downloads'),
    url(r'^lessons', TemplateView.as_view(template_name='resources/lessons.html'), name='lessons'),
    url(r'^links', TemplateView.as_view(template_name='resources/links.html'), name='links'),

    #handle all cases for now
    url(r'^images/category/(?P<category>\w+)/(?P<page>\d{1,3})/detail',
        voyages.apps.resources.views.get_image_detail,
        name='image-detail'),
    url(r'^images/category/(?P<category>\w+)/(?P<page>\d{1,3})',
        voyages.apps.resources.views.get_images_category_detail,
        name='images-category-detail'),
    url(r'^images/category/(?P<category>\w+)',
        voyages.apps.resources.views.get_images_category,
        name='images-category'),
    url(r'^images/search/(?P<page>\d{1,3})/detail',
        voyages.apps.resources.views.get_image_search_detail,
        name='image-search-detail-window'),
    url(r'^images/search/(?P<page>\d{1,3})',
        voyages.apps.resources.views.images_search_detail,
        name='images-search-detail'),
    url(r'^images/search',
        voyages.apps.resources.views.images_search,
        name='images-search'),
    url(r'^images/', voyages.apps.resources.views.get_all_images,
        name='images'),
    url(r'^names-database',
        voyages.apps.resources.views.get_all_slaves,
        name='origins')]

voyages/urls.py
from django.conf import settings
from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
from autocomplete_light import shortcuts as autocomplete_light
autocomplete_light.autodiscover()
from django.contrib import admin

admin.autodiscover()

# Sitemap
from sitemap import StaticSitemap

js_info_dict = {
    'packages': ('voyages',),
}

import voyages.apps.assessment.views
import voyages.apps.voyage.views
import voyages.apps.common.views
import voyages.apps.past.views
import django.contrib.sitemaps.views
import django.views.i18n
import django.views.static

urlpatterns = [
    url(r'^', include('voyages.apps.static_content.urls', namespace='static_content')),
    # Short permalink
    url(r'^estimates/(?P<link_id>\w+)', voyages.apps.assessment.views.restore_permalink, name='restore_e_permalink'),
    url(r'^voyages/(?P<link_id>\w+)', voyages.apps.voyage.views.restore_permalink, name='restore_v_permalink'),
    url(r'^past-db/(?P<link_id>\w+)', voyages.apps.past.views.restore_permalink, name='restore_past_permalink'),

    #Include url handlers of each section
    url(r'^voyage/', include('voyages.apps.voyage.urls', namespace='voyage')),
    url(r'^american/', include('voyages.apps.american.urls', namespace='american')),
    url(r'^assessment/', include('voyages.apps.assessment.urls', namespace='assessment')),
    url(r'^about/', include('voyages.apps.about.urls', namespace='about')),
    url(r'^common/', include('voyages.apps.common.urls', namespace='common')),
    url(r'^past/', include('voyages.apps.past.urls', namespace='past')),
    url(r'^resources/', include('voyages.apps.resources.urls', namespace='resources')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^contribute/', include('voyages.apps.contribute.urls', namespace='contribute')),
    url(r'^search/', include('haystack.urls', namespace='search')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),

    # Handle language changes
    url(r'^setlanguage/(?P<lang_code>\w+)', voyages.apps.common.views.set_language, name='set_lang'),

    # Translation support for javascript code.
    url(r'^jsi18n/', django.views.i18n.javascript_catalog, js_info_dict, name='javascript-catalog'),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^captcha/', include('captcha.urls'))]

# XML generated sitemap
sitemaps = {
    'staticpages': StaticSitemap(urlpatterns),
}
# URLs not included in the sitemap
urlpatterns += [
    url(r'^sitemap\.xml', django.contrib.sitemaps.views.sitemap, {'sitemaps': sitemaps}, name='sitemap-xml'),

    # Flatpages
    url(r'^pages/', include('django.contrib.flatpages.urls')),

    # Adding download files
    url(r'^admin/downloads', voyages.apps.voyage.views.download_file, name="downloads"),

    # Admin documentation
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Admin management
    url(r'^admin/', include(admin.site.urls))]

#Serving static files including files uploaded by users
if settings.DEBUG:
# static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^documents/(?P<path>.*)', django.views.static.serve, {
        'document_root': settings.MEDIA_ROOT})]

voyages/apps/about/views.py
from voyages.apps.common.views import render_locale_flatpage

# A catch all for URL matching
def render_about_flatpage(request, flatpage_url):
    flatpage_url = "/about/" + flatpage_url + "/"
    return render_locale_flatpage(request, 'about/flatpage.html', flatpage_url)

voyages/apps/resources/templates/resources/_personal-data.html
{% load i18n %}

<li class="nav-item dropdown">
  <v-menu-title :count="filter.personalData.count" title="{% trans 'Personal Data' %}"></v-menu-title>

  <div class="">
    <ul class="dropdown-menu search-menu" id="personalData" role="menu">

      <v-panel @apply="apply" @reset="reset" group="personalData" sub-group="name" title="{% trans 'Personal Data' %}" :filters="filter.personalData.name">
        <div slot="v-panel-header">
          <v-panel-header title="{% trans 'Personal Data' %}" description="{% trans 'Description' %}">
            <div slot="v-modal-content"></div>
          </v-panel-header>
        </div>

        <div slot="v-panel-content" slot-scope="scope">
          <v-number @change="changed"
            :filter="scope.filters.var_age">
          </v-number>

          <v-treeselect
            :filter="scope.filters.var_genre"
            @change="changed">
          </v-treeselect>

          <v-number @change="changed"
            :filter="scope.filters.var_stature">
          </v-number>
        </div>
      </v-panel>
      </ul>
  </div>
</li>

voyages/apps/resources/templates/resources/_tabs.html
{% load i18n %}

<!-- Tabs -->
<ul class="nav nav-tabs trans-tab">
  <li class="nav-item">
    <a class="nav-link active" @click="setActive('results')" href="#results" data-toggle="tab" data-target="#results">{% trans 'Results' %}</a>
  </li>
</ul>
<!-- End of Tabs -->

<!-- TabContainers -->
<div id="tabsJustifiedContent" class="tab-content">
  <div id="results" class="tab-pane fade active show">
    {% include "database/tabs/results.html" %}
  </div>  
</div>
<!-- End of TabContainers -->

voyages/apps/resources/templates/resources/about.html
{% extends "resources/base.html" %}
{% load voyage_extras %}
{% load sass_tags %}
{% load i18n %}

{% block title %} {% trans 'African Names Database - About' %} {% endblock %}

{% block content %}

<!-- CSS for Trans-Atlantic -->
<link href="{% sass_src 'scss/library/js-offcanvas@1.0.0.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/off-canvas.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/library/bootstrap-vue-2.0.0-rc.11.css' %}" rel="stylesheet" type="text/css" />

<div id="flatpage" v-cloak>
  <v-breadcrumb 
    module="{% trans 'African Names' %}"
    title="{% trans 'Understanding the Database' %}"
    @clicked="navigate"></v-breadcrumb>

  <div class="container-new">
    <div class="row row-offcanvas row-offcanvas-right">
      <div class='col-md-4 col-xs-12 col-lg-3 sidebar-offcanvas' id="sidebar">
        <v-flatpage @clicked="navigate" :list="articles"></v-flatpage>
      </div>

      <div class="col-md-8 col-xs-12 col-lg-9 ">

        <p class="hidden-md">
          <button type="button" class="btn btn-solid btn-sm" data-toggle="offcanvas">
            <div>
              <span class="fa fa-exchange-alt" style=" vertical-align: middle;"></span>
              <span>{% trans 'Toggle Sidebar' %}</span>
            </div>
          </button>
        </p>

        <div id="center-content-inner">
          <div v-html="content"></div>
        </div>

      </div>
    </div>
  </div>
</div>

<script src="{{ STATIC_URL }}scripts/library/vue@2.6.7.min.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/library/babel-polyfill@6.26.0.min.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/library/bootstrap-vue@2.0.0-rc.11.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/library/axios@0.18.0.min.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}scripts/vue/components/v-breadcrumb.js"></script>
<script src="{{ STATIC_URL }}scripts/vue/components/v-flatpage.js"></script>
<script src="{{ STATIC_URL }}scripts/vue/components/v-flatpage-data-african-about.js"></script>
<script src="{{ STATIC_URL }}scripts/vue/flatpage.js"></script>

<script type="text/javascript" src="https://npmcdn.com/js-offcanvas@1.0/dist/_js/js-offcanvas.pkgd.min.js" charset="utf-8"></script>
{% endblock %}

voyages/apps/resources/templates/resources/base.html
{% extends "base.html" %}
{% load sass_tags %}

<!-- The basic template for pages in the Education section -->
{% load i18n %}
{% block title %}{% trans 'About the Project' %}{% endblock %}

{% block csslist %}
	<link href="{% sass_src 'scss/navbar-site.scss' %}" rel="stylesheet" type="text/css" />
  <link href="{% sass_src 'scss/main.scss' %}" rel="stylesheet" type="text/css" />
	<link href="{% sass_src 'scss/past.scss' %}" rel="stylesheet" type="text/css" />
	<link href="{% sass_src 'scss/off-canvas.scss' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<link href="{% sass_src 'scss/library/js-offcanvas@1.0.0.min.css' %}" rel="stylesheet" type="text/css" />

<div class="container-new">
  <div class="row row-offcanvas row-offcanvas-right">
		<div class='col-md-4 col-xs-12 col-lg-3 sidebar-offcanvas' id="sidebar">
			{% block left-menu %}
				{% include "resources/left-menu.html" %}
			{% endblock %}
		</div>

    <div class="col-md-8 col-xs-12 col-lg-9 ">
      <p class="hidden-md">
        <button type="button" class="btn btn-solid btn-sm" data-toggle="offcanvas">
          <div>
            <span class="fa fa-exchange-alt" style=" vertical-align: middle;"></span>
            <span>{% trans 'Toggle Sidebar' %}</span>
          </div>
        </button>
      </p>
			{% block center-content %}

      {% endblock %}
		</div>
	</div>
</div>
{% endblock %}

{% block footer %}
<!-- {% include "footer.html" %} -->
{% endblock %}

voyages/apps/resources/templates/resources/image-search-detail-window.html
{% extends "base.html" %}
{% load sass_tags %}
{% load i18n %}
{% load thumbnail %}
{% load resources_extras %}

{% block csslist %}
<link href="{% sass_src 'scss/navbar-site.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/main.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/resources.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/image-galleries.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/off-canvas.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/v-component.scss' %}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block title %}{% trans 'Images' %}{% endblock %}

{% block content %}
<div class="nav-header">
	<div> {% trans "Resources - Image Galleries" %}</div>
	<div class="navbar-subtitle flex">
		<div class="navbar-subitem">
			{{ image.title|trans_log }}
		</div>
		<div class="navbar-subitem">
			<a href="{% url 'resources:images' %}">
				<div class="btn-navbar">
					<i class="fa fa-arrow-circle-left"></i>
					{% trans 'All Categories' %}
				</div>
			</a>
		</div>
	</div>
</div>

<div class="container-new">

  <div class="row  row-offcanvas row-offcanvas-right">
		<div class='col-md-4 col-xs-12 col-lg-3 sidebar-offcanvas' id="sidebar">
			{% include "resources/images-left-menu.html" %}
		</div>

    <div class="col-md-8 col-xs-12 col-lg-9 ">

			<p class="hidden-md">
        <button type="button" class="btn btn-solid btn-sm" data-toggle="offcanvas">
          <div>
            <span class="fa fa-exchange-alt" style=" vertical-align: middle;"></span>
            <span>{% trans 'Toggle Sidebar' %}</span>
          </div>
        </button>
      </p>

			<div id="center-content-inner">
				<div class="images-category page-section">
					<img src="{{ MEDIA_URL }}/{{ image.file }}" class="img-fluid"/>
				</div>
			</div>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

voyages/apps/resources/templates/resources/images-category.html
{% extends "base.html" %}
{% load sass_tags %}
{% load i18n %}
{% load thumbnail %}
{% load resources_extras %}

{% block csslist %}
<link href="{% sass_src 'scss/navbar-site.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/main.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/resources.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/image-galleries.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/off-canvas.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/v-component.scss' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block title %}{% trans 'Category Images' %}{% endblock %}

{% block content %}

<div class="nav-header">
	<div> {% trans "Resources - Image Galleries" %}</div>
	<div class="navbar-subtitle flex">
		<div class="navbar-subitem">
			{% trans 'Images of ' %}
			{% for images_set in images %}
			{% if images_set.images %}
			{{ images_set.label_name|trans_log }}
			{% for i in images %}
			{% if i.label_name == category %}
			({{ i.images|length }} {% trans 'images' %})
			{% endif %}
			{% endfor %}
			{% endif %}
			{% endfor %}
		</div>
		<div class="navbar-subitem">
			<a href="{% url 'resources:images' %}">
				<div class="btn-navbar">
					<i class="fa fa-arrow-circle-left"></i>
					{% trans 'All Categories' %}
				</div>
			</a>
		</div>
	</div>
</div>

<div class="container-new">
  <div class="row  row-offcanvas row-offcanvas-right">
		<div class='col-md-4 col-xs-12 col-lg-3 sidebar-offcanvas' id="sidebar">
			{% include "resources/images-left-menu.html" %}
		</div>
		<div class="col-md-8 col-xs-12 col-lg-9 ">

			<p class="hidden-md">
        <button type="button" class="btn btn-solid btn-sm" data-toggle="offcanvas">
          <div>
            <span class="fa fa-exchange-alt" style=" vertical-align: middle;"></span>
            <span>{% trans 'Toggle Sidebar' %}</span>
          </div>
        </button>
      </p>

			<div id="center-content-inner">
				<div class="page-title-1">
					{% trans 'Images of ' %}
					{% for images_set in images %}
					{% if images_set.images %}
					{{ images_set.label_name|trans_log }}
					{% for i in images %}
					{% if i.label_name == category %}
					({{ i.images|length }} {% trans 'images' %})
					{% endif %}
					{% endfor %}
					{% endif %}
					{% endfor %}
				</div>

				{%  for images_set in images %}
						{% if images_set.images %}
								{% for i in images %}
										{% if i.label_name == category %}
												{% for image in i.images %}
													{% ifequal forloop.counter0|modulo:4 0 %}
														<div class="row">
													{% endifequal %}

										<div class="col-md-3 col-sm-6 col-xs-12 col-lg-3 col-xl-3">
												<div class="grid-image">
													{% thumbnail image.file "100x100" as im %}
															<a href="{% url 'resources:images-category-detail' category|spaces_to_underscores forloop.counter %}"><img src="{{ im.url }}" class="img-fluid img-thumbnail"/></a>
															{% empty %}
															<a href="{% url 'resources:images-category-detail' category|spaces_to_underscores forloop.counter %}"><img src="{{ MEDIA_URL }}{{ image.file }}" class="img-fluid img-thumbnail"/></a>
													{% endthumbnail %}
												</div>

												<div class="grid-text">
														<div class="gallery-image-label">
														<a href="{% url 'resources:images-category-detail' category|spaces_to_underscores forloop.counter %}">{{ image.title|trans_log }}</a>
														</div>
														<div class="gallery-image-description">({{ image.year }})</div>
												</div>
											</div>

												{% if forloop.last or forloop.counter0|modulo:4 == 3 or forloop.las %}
													</div>
	                      {% endif %}

											{% endfor %}
									{% endif %}
							{% endfor %}



						{% endif %}
				{% endfor %}
			</div>





		</div>
	</div>
</div>












{% endblock %}


{% block footer %}
{% endblock %}

voyages/apps/resources/templates/resources/images-index.html
{% extends "base.html" %}
{% load sass_tags %}
{% load i18n %}
{% load thumbnail %}
{% load resources_extras %}

{% block csslist %}
<link href="{% sass_src 'scss/navbar-site.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/main.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/resources.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/image-galleries.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/off-canvas.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/search-ui.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/v-component.scss' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}


<div class="nav-header">
	<div> {% trans "Resources - Image Galleries" %}</div>
	<div class="navbar-subtitle flex">
		<div class="navbar-subitem">
			{% trans 'All Categories ' %}
		</div>
	</div>
</div>

<div class="container-new">

  <div class="row  row-offcanvas row-offcanvas-right">
		<div class='col-md-4 col-xs-12 col-lg-3 sidebar-offcanvas' id="sidebar">
			{% include "resources/images-left-menu.html" %}
		</div>

    <div class="col-md-8 col-xs-12 col-lg-9 ">

			<p class="hidden-md">
        <button type="button" class="btn btn-solid btn-sm" data-toggle="offcanvas">
          <div>
            <span class="fa fa-exchange-alt" style=" vertical-align: middle;"></span>
            <span>{% trans 'Toggle Sidebar' %}</span>
          </div>
        </button>
      </p>

			<div id="center-content-inner">
				<div class="page-title-1">
					{% trans 'All Categories' %}
				</div>
				{%  for images_set in images %}
						{% if images_set.images %}
								<div class="images-category page-section">
										<div class="page-title-2">{{ images_set.label_name|trans_log }}</div>
										<div class="images-category-link"><a href="{%  url 'resources:images-category' images_set.label_name|spaces_to_underscores %}">{% trans 'View all images' %}</a></div>
								</div>

								<div class="row images-category">
										{% for image in images_set.images %}
										<div class="col-md-3 col-sm-6 col-xs-12 col-lg-3 col-xl-3">
												<div class="grid-image">
												{% for key, value in image.iteritems %}
														{% if key == "file" %}
																{% thumbnail value "100x100" as im %}
																		<a href="{% url 'resources:images-category-detail' category=images_set.label_name|spaces_to_underscores page=forloop.parentloop.counter %}">
																			<img src="{{ im.url }}" class="img-fluid img-thumbnail">
																		</a>
																		{% empty %}
																				<a href="{% url 'resources:images-category-detail' category=images_set.label_name|spaces_to_underscores page=forloop.parentloop.counter %}">
																				<img src="{{ MEDIA_URL }}{{ value }}" class="img-fluid img-thumbnail">
																				</a>
																{% endthumbnail %}
														{% endif %}
												{% endfor %}
												</div>

												<div class="grid-text">
												{% for key, value in image.iteritems %}
																{% if key == "title" %}
																<div class="gallery-image-label">
																<a href="{% url 'resources:images-category-detail' category=images_set.label_name|spaces_to_underscores page=forloop.parentloop.counter %}">
																		{{ value|trans_log }}
																</a>
																</div>
																{% endif %}
																{% if key == "year" and value != 0 %}
																<div class="gallery-image-description">({{ value|trans_log }})</div>
																{% endif %}
												{% endfor %}
												</div>
											</div>
										{% endfor %}
								</div>




						{% endif %}
				{% endfor %}
			</div>
    </div>
  </div>
</div>
<script>
	$(function () {
		$('[data-toggle="tooltip"]').tooltip()
	})
</script>
{% endblock %}

{% block footer %}
{% endblock %}

voyages/apps/resources/templates/resources/images-search-detail.html
{% extends "base.html" %}
{% load sass_tags %}
{% load i18n %}
{% load thumbnail %}
{% load resources_extras %}

{% block csslist %}
<link href="{% sass_src 'scss/navbar-site.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/main.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/resources.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/image-galleries.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/off-canvas.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'scss/v-component.scss' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block title %}{% trans 'Image Detail' %}{% endblock %}

{% block content %}
<div class="nav-header">
	<div> {% trans "Resources - Image Galleries" %}</div>
	<div class="navbar-subtitle flex">
		<div class="navbar-subitem">
			{% for i in results %}
			{{ i.title|trans_log }}
			{% endfor %}
		</div>
		<div class="navbar-subitem">
			{% if not query %}
			{% if enabled_categories|length == 1 %}
			{% for i in enabled_categories %}
			<a href="{% url 'resources:get_images_category' i %}">
				<div class="btn-navbar">
					<i class="fa fa-arrow-circle-left"></i>
					{% trans 'Images of ' %}{{ i|trans_log }}
				</div>
			</a>
			{% endfor %}
			{% elif enabled_categories|length == 4 %}
			<a href="{% url 'resources:images-search' %}">
				<div class="btn-navbar">
					<i class="fa fa-arrow-circle-left"></i>
					{% trans 'All images' %}
				</div>
			</a>
			{% else %}
			<a href="{% url 'resources:images-search' %}">
				<div class="btn-navbar">
					<i class="fa fa-arrow-circle-left"></i>
					{% trans 'Search Results' %}
				</div>
			</a>
			{% endif %}
			{% else %}
			<a href="{% url 'resources:images-search' %}">
				<div class="btn-navbar">
					<i class="fa fa-arrow-circle-left"></i>
					{% trans 'Search Results' %}
				</div>
			</a>
			{% endif %}
			
		</div>
	</div>
</div>

<div class="container-new">
  <div class="row row-offcanvas row-offcanvas-right">
		<div class='col-md-4 col-xs-12 col-lg-3 sidebar-offcanvas' id="sidebar">
			{% include "resources/images-left-menu.html" %}
		</div>

    <div class="col-md-8 col-xs-12 col-lg-9 ">

			<p class="hidden-md">
        <button type="button" class="btn btn-solid btn-sm" data-toggle="offcanvas">
          <div>
            <span class="fa fa-exchange-alt" style=" vertical-align: middle;"></span>
            <span>{% trans 'Toggle Sidebar' %}</span>
          </div>
        </button>
      </p>

			<div id="center-content-inner">
				<div class="page-title-1">
					{% trans 'Image Detail' %}
				</div>

					    {% for i in results %}
								<div class='page-section'>
					            <a href="{% url 'resources:image-search-detail-window' results.number %}">
					                {% thumbnail i.file "400" as im %}
					                    <img src="{{ im.url }}" class="img-fluid">
					                    {% empty %}
					                        <img src="{{ MEDIA_URL }}{{ i.file }}" class="img-fluid">
					                {% endthumbnail %}
					            </a>
										</div>
											<div class='page-section'>

											{% if results.has_previous %}
													<a href={{ results.previous_page_number }}>{% trans 'Previous' %}</a>
											{% else %}
													{% trans 'Previous' %}
											{% endif %}

											{{ results.number }} / {{ results.paginator.num_pages }}

											{% if results.has_next %}
													<a href={{ results.next_page_number }}>{% trans 'Next' %}</a>
											{% else %}
													{% trans 'Next' %}
											{% endif %}
											</div>

					            <div class="page-section">
					                {{ i.description|trans_log }}
					            </div>

											<div class="page-section">
					            <div class="page-title-2">
												Metadata
											</div>
										  <table class="table">
					                <tbody>
					                {% if i.date %}
					                    <tr>
					                        <td>
					                            <div class="image-detail-info-label">
					                                {% trans 'Year' %}
					                            </div>
					                        </td>
					                        <td>
					                            {{ i.date }}
					                        </td>
					                    </tr>
					                {% endif %}
					                <tr>
					                    <td>
					                        <div class="image-detail-info-label">
					                            {% trans 'Source' %}
					                        </div>
					                    </td>
					                    <td>
					                        {{ i.source }}
					                    </td>
					                </tr>
					                {% if i.language %}
					                <tr>
					                    <td>
					                        <div class="image-detail-info-label">
					                            {% trans 'Language' %}
					                        </div>
					                    </td>
					                    <td>
					                        {{ i.language|decode_language }}
					                    </td>
					                </tr>
					                {% endif %}
					                </tbody>
					            </table>
											</div>

					            {% if i.voyage_vessel_name %}
											<div class="page-section">
						            <div class="page-title-2">
													{% trans 'Related Voyages' %}
												</div>
                        {% trans 'Voyage ID' %} =
                        {{ i.voyage_id }} - {{ i.voyage_vessel_name }}, {{ i.voyage_imp_voyage_began|get_year_value }}
											</div>
											{% endif %}

    			{% endfor %}

				</div>
				</div>
				</div>

{% endblock %}


{% block footer %}
{% endblock %}

voyages/apps/resources/templates/resources/left-menu.html
<!-- Left side menu for the About section -->

{% load i18n %}

<div class="sidebar-header-container">
	<div class="sidebar-title-1">{% trans "About this Database" %}</div>
</div>

<div class="sidebar-section">
<div class="secondary-menu-item-0" id="history">
	<a href="{% url 'resources:about' %}">{% trans "About" %}</a>
</div>
</div>